spring:
  graphql:
    exception-handlers-enabled: true
    graphiql:
      enabled: true
  config:
    import: optional:file:env.properties
  application:
    name: ${NAME_APP:app}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        envers:
          audit_table_suffix: _aud
          enabled: true
          default_schema: ${DB_SCHEMA_AUDIT}
          default_suffix: _AUD
          auto_register_listeners: true
        format_sql: true
        default_schema: ${DB_SCHEMA}
    database: postgresql
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgres
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
    resolve-schema-properties: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: false
server:
  error:
    include-stacktrace: never
api:
  security:
    jwt:
      secret: ${JWT_SECRET:123456}
      expiration: ${JWT_EXPIRATION}